spring:
  application:
    name: ${APPLICATION_NAME:tutor-requirement-search-service}

  kafka:
    consumer:
      bootstrap-servers: ${KAFKA_BOOTSTRAP_SERVER:localhost:9092}
      group-id: ${KAFKA_CONSUMER_GROUP_ID:services-group}

    custom:
      enable-listeners: ${KAFKA_ENABLE_LISTENERS:true}
      tutor-requirement-topic: ${KAFKA_TUTOR_REQUIREMENT_TOPIC:tutor-requirement-events}


  cache:
    type: redis
  redis:
    host: ${REDIS_HOST:localhost}
    port: ${REDIS_PORT:6379}
    password: ${REDIS_PASSWORD:redis-pass}

  sleuth:
    enabled: ${SLEUTH_ENABLED:true}
    sampler:
      probability: 1

  zipkin:
    enabled: ${ZIPKIN_ENABLED:true}
    base-url: ${ZIPKIN_URL:http://localhost:9411/}

app:
  elastic:
    host: ${ELASTIC_HOST:localhost}
    port: ${ELASTIC_PORT:9200}
    username: ${ELASTIC_USERNAME:}
    password: ${ELASTIC_PASSWORD:}

  jwt:
    token:
      secret-key: ${JWT_SECRET_KEY:secret}
      expiry: 100000

server:
  port: ${SERVER_PORT:8081}

management:
  endpoint:
    metrics:
      enabled: true
    prometheus:
      enabled: true
  endpoints:
    web:
      exposure:
        include: health,info,prometheus
