spring:
  application:
    name: ${APPLICATION_NAME:student-service}

  kafka:
    producer:
      bootstrap-servers: ${KAFKA_BOOTSTRAP_SERVER:localhost:9092}
    consumer:
      bootstrap-servers: ${KAFKA_BOOTSTRAP_SERVER:localhost:9092}
      group-id: ${KAFKA_CONSUMER_GROUP_ID:group}

    custom:
      student-signup-topic: ${KAFKA_STUDENT_SIGNUP_TOPIC:student-signup-events}
      student-signup-email-topic: ${KAFKA_STUDENT_SIGNUP_EMAIL_TOPIC:student-signup-email-events}
      enable-listeners: ${KAFKA_ENABLE_LISTENERS:true}

  data:
    mongodb:
      username: ${MONGO_USERNAME:mongo}
      password: ${MONGO_PASSWORD:mongo}
      database: ${MONGO_DATABASE:student-db}
      port: 27017
      host: ${MONGO_URL:localhost}
      auto-index-creation: true

  sleuth:
    sampler:
      percentage: 1

  zipkin:
    enabled: ${ZIPKIN_ENABLED:true}
    base-url: ${ZIPKIN_URL:http://localhost:9411/}

app:
  jwt:
    token:
      secret-key: ${JWT_SECRET_KEY:secret}
      expiry: 100000

management:
  endpoint:
    metrics:
      enabled: true
    prometheus:
      enabled: true
  endpoints:
    web:
      exposure:
        include: health,info,prometheus

resilience4j:
  circuitbreaker:
    configs:
      default:
        registerHealthIndicator: true
    instances:
      defaultsForCandidateServiceApp:
        minimumNumberOfCalls: 5
        failureRateThreshold: 50
        waitDurationInOpenState: 30000
        permitNumberOfCallsInHalfOpenState: 2

  retry:
    configs:
      default:
        registerHealthIndicator: true
    instances:
      retryForCandidates:
        maxRetryAttempts: 3
        waitDuration: 2000

server:
  port: 8084
