apiVersion: v1
kind: Service
metadata:
  name: authentication-service
  annotations:
    cloud.google.com/neg: '{"ingress": true}'
spec:
  selector:
    app: auth-app
  ports:
    - port: 80
      #      nodePort: 30070 # exposing to local, to access this service
      targetPort: 8080
  type: ClusterIP
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: authentication-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: auth-app
  template:
    metadata:
      labels:
        app: auth-app
    spec:
      containers:
        - name: auth-app
          image: vishwaghimire/authentication-service
          imagePullPolicy: Always
          ports:
            - containerPort: 8080
          env:
            # Database: MySQL
            - name: MYSQL_URL
              valueFrom:
                configMapKeyRef:
                  name: core-configs
                  key: mysql_url
            - name: MYSQL_DB_NAME
              valueFrom:
                configMapKeyRef:
                  name: core-configs
                  key: mysql_authDBName
            - name: MYSQL_USERNAME
              value: root
            - name: MYSQL_PASSWORD
              value: root

            - name: KAFKA_BOOTSTRAP_SERVER
              valueFrom:
                configMapKeyRef:
                  name: core-configs
                  key: kafka_BootStrapServers
            - name: KAFKA_CONSUMER_GROUP_ID
              valueFrom:
                configMapKeyRef:
                  name: core-configs
                  key: kafka_searchServiceGroupId
            - name: KAFKA_TUTOR_SIGNUP_TOPIC
              valueFrom:
                configMapKeyRef:
                  name: core-configs
                  key: tutor-signup-topic
            - name: KAFKA_STUDENT_SIGNUP_TOPIC
              valueFrom:
                configMapKeyRef:
                  name: core-configs
                  key: student-signup-topic
            - name: KAFKA_RESERVATION_TOPIC
              valueFrom:
                configMapKeyRef:
                  name: core-configs
                  key: reservation-topic
            - name: KAFKA_STUDENT_DETAIL_RESERVATION_TOPIC
              valueFrom:
                configMapKeyRef:
                  name: core-configs
                  key: student-detail-after-reservation-email-topic
            - name: KAFKA_RESERVATION_APPROVED_TOPIC
              valueFrom:
                configMapKeyRef:
                  name: core-configs
                  key: reservation-approved-topic
            - name: KAFKA_RESERVATION_APPROVED_EMAIL_TOPIC
              valueFrom:
                configMapKeyRef:
                  name: core-configs
                  key: reservation-approved-email-topic

            # Tracing: Zipkin & Sleuth
            - name: ZIPKIN_URL
              valueFrom:
                configMapKeyRef:
                  name: core-configs
                  key: zipkin_url
            - name: ZIPKIN_ENABLED
              value: 'true'

            # App Specific
            - name: JWT_SECRET_KEY
              valueFrom:
                secretKeyRef:
                  name: core-secrets
                  key: jwt-secret-key